// Generated by scripts/generate-sdk-types.mjs from the app's own input checks.
// Do not edit by hand: change the zod schema in src/ and run the script again.

export interface RunInput {
    prompt: string;
    sessionId?: string;
    temporary?: boolean;
    checks?: {
      [key: string]: unknown;
    };
    dryRun?: boolean;
    images?: ({
      mediaType: "image/png" | "image/jpeg" | "image/webp" | "image/gif";
      data: string;
      name?: string;
    })[];
    plan?: boolean;
    verify?: boolean;
  }

export interface Policy {
    preset?: "off" | "ask-before-changes" | "workspace" | "read-only" | "custom";
    rules?: ({
      tool?: string;
      match?: string;
      applies?: "any" | "changes";
      decision: "allow" | "ask" | "deny";
      remember?: "never" | "session" | "always";
    })[];
    limits?: {
      toolCallsPerMinute?: number;
      modelRoundsPerMinute?: number;
    };
  }

export interface PolicyRule {
    tool?: string;
    match?: string;
    applies?: "any" | "changes";
    decision: "allow" | "ask" | "deny";
    remember?: "never" | "session" | "always";
  }

export interface PolicyInput {
    preset?: "off" | "ask-before-changes" | "workspace" | "read-only" | "custom";
    rules?: ({
      tool?: string;
      match?: string;
      applies?: "any" | "changes";
      decision: "allow" | "ask" | "deny";
      remember?: "never" | "session" | "always";
    })[];
    limits?: {
      toolCallsPerMinute?: number;
      modelRoundsPerMinute?: number;
    };
  }

export interface DocumentSearch {
    query: string;
    limit?: number;
  }

export interface DocumentSettings {
    useDocuments?: boolean;
    embeddingModel?: string;
  }

export interface MemoryRetrievalSettings {
    useEmbeddings?: boolean;
    embeddingModel?: string;
  }

export interface AuditEntryInput {
    action: "approval.decided" | "secret.used" | "policy.changed" | "channel.paired" | "data.exported" | "profile.switched" | "practice.switched";
    actor?: string;
    subject?: string;
    reason?: string;
    source?: "owner" | "trigger" | "schedule" | "mcp" | "system";
    runId?: string | null;
    outcome?: string;
  }

export interface AuditQuery {
    action?: "approval.decided" | "secret.used" | "policy.changed" | "channel.paired" | "data.exported" | "profile.switched" | "practice.switched";
    source?: "owner" | "trigger" | "schedule" | "mcp" | "system";
    from?: string;
    to?: string;
    limit?: number;
  }

export interface CategoryDecisions {
    read?: "allow" | "ask" | "deny";
    files?: "allow" | "ask" | "deny";
    commands?: "allow" | "ask" | "deny";
    browse?: "allow" | "ask" | "deny";
    message?: "allow" | "ask" | "deny";
    spend?: "allow" | "ask" | "deny";
    settings?: "allow" | "ask" | "deny";
  }

export interface AskFirstSettings {
    askFirst?: boolean;
    maxQuestions?: number;
  }

export interface AskFirstRequest {
    prompt: string;
    askFirst?: boolean;
  }

export interface AskFirstAnswers {
    prompt: string;
    answers?: ({
      question: string;
      answer?: string;
    })[];
  }

export interface ClarifyingQuestion {
    question: string;
    suggested?: string;
  }

export interface RerankSettings {
    mode?: "words" | "model";
    candidates?: number;
    keep?: number;
  }

export interface PracticeSwitch {
    practice: boolean;
  }

export interface ProviderPresetInput {
    driver: string;
    preset: string;
    name: string;
    endpoint: string;
    model: string;
    apiKey?: string;
  }

export interface IssueLink {
    url: string;
  }


export interface RunEvent { kind: string; id?: number; data?: Record<string, unknown>; createdAt?: string; status?: string }
export interface AuditEntry {
  id: number; owner: string; at: string; action: string; actor: string;
  subject: string; reason: string; source: string; runId: string | null; outcome: string;
}
export interface RetrievedPassage { key: string; source: string; text: string; score: number; from: string }
export interface AskFirstOutcome { skipped: boolean; reason: string; questions: ClarifyingQuestion[] }
export interface ClientOptions { url: string; token: string; fetch?: typeof fetch; timeoutMs?: number }

export declare class BranchError extends Error { status: number; path?: string }
export declare function fromDataDir(dataDir: string, options?: { readFile?: unknown; port?: number }): Promise<BranchClient>;

export declare class BranchClient {
  constructor(options: ClientOptions);
  readonly url: string;
  state(): Promise<Record<string, unknown>>;
  tools(): Promise<Record<string, unknown>>;
  audit(filters?: AuditQuery): Promise<{ entries: AuditEntry[]; counts: { action: string; label: string; count: number }[] }>;
  action(tool: string, args?: Record<string, unknown>): Promise<unknown>;
  askFirst(prompt: string, askFirst?: boolean): Promise<AskFirstOutcome>;
  withAnswers(prompt: string, answers: AskFirstAnswers["answers"]): Promise<{ prompt: string; added: number }>;
  search(query: string): Promise<{ passages: RetrievedPassage[]; reranked: string; rerankCalls: number; note: string }>;
  issueContext(url: string): Promise<{ text: string; sources: string[]; citations: string[] }>;
  request(method: string, path: string, body?: unknown, options?: { signal?: AbortSignal; timeoutMs?: number }): Promise<unknown>;
  get(path: string): Promise<unknown>;
  post(path: string, body?: unknown): Promise<unknown>;
  readonly runs: {
    start(input: RunInput): Promise<{ id: string; sessionId: string; status: string; output: string }>;
    get(runId: string): Promise<Record<string, unknown>>;
    steer(runId: string, text: string): Promise<{ queued: number }>;
    cancel(runId: string): Promise<{ cancelled: boolean }>;
    resume(runId: string): Promise<Record<string, unknown>>;
    approve(sessionId: string, decision: "allow" | "deny", remember?: "never" | "session" | "always"): Promise<Record<string, unknown>>;
    receipts(runId: string): Promise<Record<string, unknown>>;
    activity(): Promise<Record<string, unknown>[]>;
    stream(runId: string, options?: { after?: number; signal?: AbortSignal }): AsyncGenerator<RunEvent>;
    watch(runId: string, options?: { signal?: AbortSignal }): AsyncGenerator<RunEvent>;
  };
  readonly sessions: {
    get(sessionId: string): Promise<Record<string, unknown>>;
    search(input: Record<string, unknown>): Promise<Record<string, unknown>>;
    summary(sessionId: string): Promise<Record<string, unknown>>;
    export(sessionId: string): Promise<Record<string, unknown>>;
    followUp(sessionId: string, prompt: string): Promise<Record<string, unknown>>;
  };
  readonly memory: {
    search(query: string, limit?: number): Promise<{ results: Record<string, unknown>[] }>;
    export(): Promise<Record<string, unknown>>;
    index(): Promise<{ embedded: number; reason: string }>;
    settings(): Promise<{ settings: MemoryRetrievalSettings; meaningSearch: boolean; ranked: boolean }>;
    configure(input: Partial<MemoryRetrievalSettings>): Promise<MemoryRetrievalSettings>;
  };
  readonly documents: {
    list(): Promise<Record<string, unknown>>;
    add(input: { name?: string; path?: string; text?: string; content?: string }): Promise<Record<string, unknown>>;
    search(query: string, limit?: number): Promise<{ results: Record<string, unknown>[] }>;
    remove(id: string): Promise<{ removed: string }>;
    settings(): Promise<DocumentSettings>;
  };
  readonly schedules: {
    get(scheduleId: string): Promise<Record<string, unknown>>;
    trigger(scheduleId: string): Promise<Record<string, unknown>>;
  };
  readonly policy: {
    get(): Promise<{ policy: Policy; presets: unknown[]; waiting: unknown[] }>;
    save(input: PolicyInput): Promise<{ policy: Policy }>;
    approve(sessionId: string, decision: "allow" | "deny", remember?: "never" | "session" | "always"): Promise<Record<string, unknown>>;
    categories(): Promise<{ categories: unknown[] }>;
    setCategories(decisions: CategoryDecisions): Promise<{ policy: Policy; categories: unknown[] }>;
  };
}
export default BranchClient;
