import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const contributorInstructions = [
  "docs/agents/briefs/wave1/BUILD.md",
  "docs/agents/briefs/mac1/BUILD-MAC.md",
  "docs/agents/HANDOFF-2026-09-17-cloud.md",
];

test("shipped source and contributor instructions carry no AI-tool attribution watermark", async () => {
  const product = await readFile(join(root, "public/settings-index.js"), "utf8");
  assert.doesNotMatch(product, /claude-session-files|generated by claude/i);
  for (const path of contributorInstructions) {
    const text = await readFile(join(root, path), "utf8");
    assert.doesNotMatch(text, /Co-Authored-By:\s*Claude/i, path);
  }
});
